# Generated by Django 5.0.6 on 2025-04-02 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entradamanutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisicao', models.IntegerField(max_length=6, verbose_name='requisição')),
                ('ano', models.IntegerField(max_length=4, verbose_name='Ano')),
                ('local', models.CharField(max_length=30, verbose_name='Local')),
                ('patrimonio', models.IntegerField(max_length=11, verbose_name='Patrimônio')),
                ('solicitante', models.CharField(max_length=30, verbose_name='Solicitante')),
                ('equipamento', models.CharField(max_length=30, verbose_name='Equipamento')),
                ('dataentrada', models.DateField(error_messages={'invalid': 'Essa data não e valida'}, verbose_name='Data de Entrada')),
                ('dataconclusao', models.DateField(null=True, verbose_name='Data Conclusão')),
                ('concluido', models.CharField(max_length=1, null=True, verbose_name='Concluido')),
            ],
        ),
        migrations.CreateModel(
            name='RetiradaEquip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ret_ent', models.CharField(choices=[('R', 'Retirado'), ('E', 'Entregue')], default='------', max_length=1, verbose_name='STATUS')),
                ('data_saida', models.DateField(blank=True, error_messages={'invalid': 'Essa data não e valida'}, verbose_name='Data de Saída')),
                ('responsavel', models.CharField(max_length=30, verbose_name='Responsavel')),
                ('matricula', models.IntegerField(max_length=11, verbose_name='Matricula')),
                ('Equipamanto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.entradamanutencao')),
            ],
        ),
    ]
