# Generated by Django 5.0.6 on 2025-03-28 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradamanutencao',
            name='data_saida',
        ),
        migrations.RemoveField(
            model_name='entradamanutencao',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='entradamanutencao',
            name='responsavel',
        ),
        migrations.RemoveField(
            model_name='entradamanutencao',
            name='ret_ent',
        ),
        migrations.RemoveField(
            model_name='entradamanutencao',
            name='retirado',
        ),
        migrations.CreateModel(
            name='RetiradaEquip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ret_ent', models.CharField(choices=[('R', 'Retirado'), ('E', 'Entregue')], default='------', max_length=1, verbose_name='STATUS')),
                ('data_saida', models.DateField(blank=True, verbose_name='Data de Saída')),
                ('responsavel', models.CharField(max_length=30, verbose_name='Responsavel')),
                ('matricula', models.IntegerField(verbose_name='Matricula')),
                ('Equipamanto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.entradamanutencao')),
            ],
        ),
    ]
