# Generated by Django 5.0.6 on 2025-04-10 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retiradaequip',
            old_name='equipamento',
            new_name='equipamentoret_ent',
        ),
    ]
