# Generated by Django 5.0.6 on 2025-04-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradamanutencao',
            name='requisicao',
            field=models.CharField(max_length=6, verbose_name='requisição'),
        ),
    ]
