# Generated by Django 5.0.6 on 2025-04-16 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_rename_equipamento_retiradaequip_equipamentoret_ent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retiradaequip',
            name='equipamentoret_ent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='todos.entradamanutencao', verbose_name='equipamento'),
        ),
    ]
