# Generated by Django 5.0.6 on 2025-04-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_entradamanutencao_requisicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradamanutencao',
            name='ano',
            field=models.CharField(max_length=4, verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='entradamanutencao',
            name='patrimonio',
            field=models.CharField(max_length=11, verbose_name='Patrimônio'),
        ),
        migrations.AlterField(
            model_name='retiradaequip',
            name='matricula',
            field=models.CharField(max_length=11, verbose_name='Matricula'),
        ),
    ]
