# Generated by Django 5.0.6 on 2025-03-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_remove_entradamanutencao_data_saida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retiradaequip',
            name='data_saida',
            field=models.DateField(blank=True, error_messages={'invalid': 'Essa data não e valida'}, verbose_name='Data de Saída'),
        ),
    ]
