# Generated by Django 5.0.6 on 2025-04-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_alter_retiradaequip_data_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradamanutencao',
            name='dataentrada',
            field=models.DateField(error_messages={'invalid': 'Essa data não e valida'}, verbose_name='Data de Entrada'),
        ),
    ]
