# Generated by Django 5.0.6 on 2025-04-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_alter_entradamanutencao_dataentrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradamanutencao',
            name='ano',
            field=models.IntegerField(max_length=4, verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='entradamanutencao',
            name='patrimonio',
            field=models.IntegerField(max_length=11, verbose_name='Patrimônio'),
        ),
        migrations.AlterField(
            model_name='entradamanutencao',
            name='requisicao',
            field=models.IntegerField(max_length=6, verbose_name='requisição'),
        ),
        migrations.AlterField(
            model_name='retiradaequip',
            name='matricula',
            field=models.IntegerField(max_length=11, verbose_name='Matricula'),
        ),
    ]
